function mydialog2
    d = dialog('Position',[450 400 250 150],'Name','INFORMATION');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','Si vous voulez des informations sur les angles et la symétrie, veuillez choisir "TOUS" dans la boîte de dialogue ci-contre.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','OK',...
               'Callback','delete(gcf)');
end

