function mydialog3
    d = dialog('Position',[450 400 250 150],'Name','INFORMATION');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','Les graphiques ont bien été sauvegardés dans votre dossier de référence MATLAB.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','OK',...
               'Callback','delete(gcf)');
end

