function mydialog
    d = dialog('Position',[450 400 250 150],'Name','INFORMATION');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','Vous allez devoir choisir le fichier que vous voulez analyser dans 5 secondes.');

    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','OK',...
               'Callback','delete(gcf)');
end

